import type { Metadata } from "next";
import { initDB } from "./database/init";
import { CssBaseline, CssVarsProvider, Stack } from "@mui/joy";
import { Inter } from "next/font/google";
import Contacts from "./components/contacts";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  initDB();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CssVarsProvider>
          <CssBaseline />
          <Stack
            height="100vh"
            direction="row"
            component="main"
            id="main-content"
          >
            {children}
          </Stack>
        </CssVarsProvider>
      </body>
    </html>
  );
}
